services: 
  - name: geth
    image: "ethereum/client-go:alltools-latest" 
    script:
      inline: geth --nousb --datadir ./geth/ init /geth/genesis.json && geth --datadir ./geth/ --http --http.addr 0.0.0.0 --miner.gasprice=1 --http.api "admin,web3,eth,net,personal,miner,txpool" --http.corsdomain "0.0.0.0" --txpool.nolocals --http.vhosts=* --verbosity=5 --port 30303 --networkid 555555 --nousb --etherbase 0 --unlock 0 --allow-insecure-unlock --password ./geth/pw.txt --mine --miner.threads=6 --bootnodes enode://04eab89943b5b2aa38745051471b31dc09d187c99b8fc6b740a8587ac43d1d65d644086a862189bc6298198453ba68076ebdb9cd7013d8893878f628a664376e@${GETH_SERVICE0_COMMON_NETWORK}:30303?discport=30303
    input-files:
      - source-path: genesis.json
        destination-path: /geth/genesis.json
      - source-path: ./keystore/pk$_n
        destination-path: /geth/keystore/pk
      - source-path: ./keystore/pw.txt
        destination-path: /geth/pw.txt
      - source-path: ./keystore/nodekey$_n
        destination-path: /geth/geth/nodekey
    resources:
      cpus: 4
      memory: 6 GB
      storage: 30 GiB
  - name: record
    image: gcr.io/whiteblock/ethereum/record:latest
    script:
      inline:
        app --target http://$GETH_SERVICE0_COMMON_NETWORK:8545
    resources:
      cpus: 1
      memory: 1 GiB
      storage: 10 GiB
tests: 
  - name: geth_network_2_nodes 
    phases:
      - name: start
        system: 
        - type: geth
          count: 2
          port-mappings:
            - "$_dist_ports(8545):8545"
          resources: 
            networks: 
              - name: common-network
        - type: record
          duration: 3h
          count: 1
          port-mappings:
            - "8080:8080"
          resources:
            networks:
              - name: common-network

